### ISSUE TITLE
Camera not working on Samsung Galaxy Note II

### ISSUE THREAD

**Issue by kekzoz** [webcamoid/webcamoid#769]
Hi there,

Firstly - thanks for this cool app.  I am hoping to get it working on my Samsung Galaxy Note II phone, which has fair upstream kernel support for its rear camera.

I cross-compiled 9.3.0 for postmarketOS (Alpine-based Linux distribution) for armv7 (on my x86_64 Ubuntu laptop).  On the phone, when my pipeline is set, I can get images fine using `gst-launch-1.0 v4l2src device=/dev/video1 ! videoconvert ! video/x-raw,format=VYUY,width=1280,height=720,framerate=15/1 ! videoconvert ! glimagesink`

Starting webcamoid, I see it finds the video device I want:
```
[2025-12-29 22:03:10.411, Webcamoid, 0xb6f2c810,  (0)] info: V4L2 video device node found: "/dev/video1"
[2025-12-29 22:03:10.665, Webcamoid, 0xb6f2c810,  (0)] info: Detected camera: "exynos4-fimc" ( "/dev/video1" )
```

but then the next 17 lines are about unknown pixel formats (four of them listed below):
```
[2025-12-29 22:03:10.674, Webcamoid, 0xb6f2c810,  (0)] warning: Unknown pixel format: 1448695129 ( "YUYV" )
[2025-12-29 22:03:10.674, Webcamoid, 0xb6f2c810,  (0)] warning: Unknown pixel format: 1498831189 ( "UYVY" )
[2025-12-29 22:03:10.674, Webcamoid, 0xb6f2c810,  (0)] warning: Unknown pixel format: 1498765654 ( "VYUY" )
[2025-12-29 22:03:10.674, Webcamoid, 0xb6f2c810,  (0)] warning: Unknown pixel format: 1431918169 ( "YVYU" )
```

VYUY looks like it should work from webcamoid/libAvKys/Plugins/VideoCapture/src/capture/v4l2sys/src/capturev4l2.cpp

Any ideas about what I ought to do to get it to work?

Thanks a lot!

jack_kekzoz

Useful info:

```
samsung-t0lte:~$ v4l2-ctl --list-formats
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture Multiplanar

	[0]: 'RGBP' (16-bit RGB 5-6-5)
	[1]: 'BGRH' (18-bit BGRX 6-6-6-14)
	[2]: 'BGR4' (32-bit BGRA/X 8-8-8-8)
	[3]: 'RGBO' (16-bit A/XRGB 1-5-5-5)
	[4]: 'R444' (16-bit A/XRGB 4-4-4-4)
	[5]: 'YUYV' (YUYV 4:2:2)
	[6]: 'UYVY' (UYVY 4:2:2)
	[7]: 'VYUY' (VYUY 4:2:2)
	[8]: 'YVYU' (YVYU 4:2:2)
	[9]: '422P' (Planar YUV 4:2:2)
	[10]: 'NV16' (Y/UV 4:2:2)
	[11]: 'NV61' (Y/VU 4:2:2)
	[12]: 'YU12' (Planar YUV 4:2:0)
	[13]: 'NV12' (Y/UV 4:2:0)
	[14]: 'NM12' (Y/UV 4:2:0 (N-C))
	[15]: 'YM12' (Planar YUV 4:2:0 (N-C))
	[16]: 'TM12' (Y/UV 4:2:0 (64x32 MB, N-C))
```

```
samsung-t0lte:~$ v4l2-ctl -d /dev/video1 -D
Driver Info:
	Driver name      : exynos4-fimc
	Card type        : exynos4-fimc
	Bus info         : platform:soc:camera@11800000
	Driver version   : 6.16.10
	Capabilities     : 0x84201000
		Video Capture Multiplanar
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04201000
		Video Capture Multiplanar
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : s5p-fimc-md
	Model            : Samsung S5P FIMC
	Serial           : 
	Bus info         : platform:soc:camera@11800000
	Media version    : 6.16.10
	Hardware revision: 0x00000000 (0)
	Driver version   : 6.16.10
Interface Info:
	ID               : 0x03000007
	Type             : V4L Video
Entity Info:
	ID               : 0x00000005 (5)
	Name             : fimc.0.capture
	Function         : V4L2 I/O
	Pad 0x01000006   : 0: Sink
	  Link 0x02000048: from remote pad 0x1000004 of entity 'FIMC.0' (Video Scaler): Data, Enabled, Immutable
```

**Comment by kekzoz** [comment]
It is worth saying libcamera cannot be used on this device currently.

**Comment by hipersayanX** [comment]
I think it could be a simple problem of endianness or because the global objects are not properly solved by the compiler, because those formats are actually supported, however I will check it tomorrow, I will need you to test it since I can't test it my self.

**Comment by kekzoz** [comment]
Sure thing. Thanks.

**Comment by kekzoz** [comment]
You mentioned endianness - this was in the log from opening the app: `[2025-12-30 10:09:33.324, Webcamoid, 0xb6f09810,  (0)] info: Build ABI: "arm-little_endian-ilp32-eabi-hardfloat"` - not sure if that helps.

**Comment by kekzoz** [comment]
Compiling on device gives the same results.

**Comment by kekzoz** [comment]
Ok, there are fewer `Unknown pixel format` warnings now (but still some remain - looks like genuinely unsupported ones).  However the camera still isn't being listed as a capture source,  with nothing displayed.  Full log is here: https://pastebin.com/GXuMYF5Z

Any help is appreciated.

**Comment by kekzoz** [comment]
Thanks for fixing the format error though.

**Comment by kekzoz** [comment]
Hi again, sorry for the delay.

> It must show the camera with a resolution of 640x480, on how you explain it, it appears it only show the window but does not capture the camera. There are other cameras in /dev/video*, right? did you tried testing the other cameras? same results?

The window was blank, nothing was displayed.  The other video devices are either alternative endpoints for the pipeline (and only one of the alternatives (/dev/video3) works currently, giving exactly the same results as if I was using /dev/video1), or different media entities unrelated to camera stuff.

> But you mentioned that Cheese works, and Cheese use Pipewire from GStreamer (and Pipewire use V4L2 internally). Did you tried selecting Pipewire as capture framework in Webcamoid?
Try installing GStreamer with all the plugins and tools:

Tried selecting pipewire in webcamoid, nothing happened.  Also the below command errored out:
```
samsung-t0lte:~$ gst-launch-1.0 pipewiresrc ! videoconvert ! autovideosink
Setting pipeline to PAUSED ...
ERROR: from element /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0: stream error: target not found
Additional debug info:
../src/gst/gstpipewiresrc.c(748): on_state_changed (): /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0
ERROR: pipeline doesn't want to preroll.
Failed to set pipeline to PAUSED.
Setting pipeline to NULL ...
Freeing pipeline ...
```
Defining a resolution gave the same output.

v4l2src does work though - both the command you gave above and the one I stated in my first post:

`gst-launch-1.0 v4l2src device=/dev/video1 ! videoconvert ! video/x-raw,format=VYUY,width=1280,height=720,framerate=15/1 ! videoconvert ! glimagesink`

**Comment by kekzoz** [comment]
Oh!  For some reason `ffplay -f v4l2 -input_format yuyv422 -video_size 1280x720 /dev/video1` now works - camera is shown!  640x480 works too but is distorted.  1280x720 is the resolution I have set the pipeline to be.
